"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { CATEGORIES, type Item, type JudgeResponse } from "@/lib/types";
const labels = { high: "高い", maybe: "可能性あり", low: "低い", unknown: "判定不能" };
const photoTips = ["登録写真と同じ角度で撮る", "ロゴやタグが読める距離で撮る", "傷、汚れ、シール、名前などの目印を入れる", "靴ならソール、かかと、履きジワも写す"];

export function JudgeForm() {
  const [file, setFile] = useState<File | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [result, setResult] = useState<JudgeResponse | null>(null);
  const [items, setItems] = useState<Item[]>([]); const [category, setCategory] = useState("");
  const url = useMemo(() => file ? URL.createObjectURL(file) : "", [file]);
  const filteredItems = useMemo(() => category ? items.filter((item) => item.category === category) : items, [category, items]);
  useEffect(() => () => { if (url) URL.revokeObjectURL(url); }, [url]);
  useEffect(() => { let active = true; fetch("/api/items").then((response) => response.ok ? response.json() : []).then((json) => { if (active) setItems(Array.isArray(json) ? json : []); }).catch(() => { if (active) setItems([]); }); return () => { active = false; }; }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!category) return setError("比較するジャンルを選んでください"); if (!filteredItems.length) return setError("このジャンルの登録品がありません"); if (!file) return setError("写真を選んでください"); setError(""); setResult(null); setLoading(true); const data = new FormData(event.currentTarget); data.set("photo", file); try { const response = await fetch("/api/judge", { method: "POST", body: data }); const json = await response.json(); if (!response.ok) throw new Error(json.error || "判定に失敗しました"); setResult(json); } catch (e) { setError(e instanceof Error ? e.message : "判定に失敗しました"); } finally { setLoading(false); } }
  return <><form className="card form" onSubmit={submit}><section className="judgeStep"><p className="eyebrow">先にジャンルを選択</p><label>比較するジャンル<select name="category" value={category} required onChange={(e) => setCategory(e.target.value)}><option value="">選択してください</option>{CATEGORIES.map((x) => <option key={x}>{x}</option>)}</select></label>{items.length === 0 && <p className="hint">先に自分の物を登録すると、ジャンル内で照合できます。</p>}{category && filteredItems.length > 0 && <p className="hint">{category}の登録品 {filteredItems.length} 件すべてと照合します。</p>}{items.length > 0 && category && filteredItems.length === 0 && <p className="hint">このジャンルの登録品がありません。</p>}</section><label>判定したい物の写真<input name="photo" type="file" accept="image/*" capture="environment" required disabled={!category || filteredItems.length === 0} onChange={(e) => setFile(e.target.files?.[0] ?? null)} /></label><section className="hint photoTips" aria-label="照合時の推奨撮影ポイント"><b>推奨撮影ポイント</b><ul>{photoTips.map((tip) => <li key={tip}>{tip}</li>)}</ul></section>{url && <img className="judgePreview" src={url} alt="判定する写真のプレビュー" />}{error && <p className="error" role="alert">{error}</p>}<button className="button" disabled={loading || !category || filteredItems.length === 0}>{loading ? "AIが写真を比べています…" : "判定する"}</button></form>{result && <section className={`card result ${result.result}`} aria-live="polite"><p className="eyebrow">自分の物かどうか</p><h2>{labels[result.result]}</h2><p><b>一致候補：</b>{result.matchedItemName || "なし"}</p><p><b>信頼度：</b>{result.confidence} / 100</p><p><b>理由：</b>{result.reason}</p><p className="warning">AI判定なので最終確認は人が行ってください。</p></section>}</>;
}
